# Generated by Django 5.2.7 on 2025-10-16 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests_psy', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='symbolereference',
            unique_together={('page', 'ligne', 'position')},
        ),
        migrations.RemoveField(
            model_name='symbolereference',
            name='date_passation',
        ),
        migrations.RemoveField(
            model_name='symbolereference',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='symbolereference',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='symbolereference',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='symbolereference',
            name='psychologue',
        ),
    ]
