# Generated by Django 5.2.7 on 2025-11-30 12:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_license_has_beck_license_max_tests_beck'),
        ('cabinet', '0001_initial'),
        ('tests_psy', '0003_domain_niveauadaptatif_notedomainevmapping_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemBeck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(unique=True, verbose_name="Numéro de l'item")),
                ('categorie', models.CharField(help_text='Ex: Tristesse, Pessimisme, Échec, etc.', max_length=100, verbose_name='Catégorie')),
            ],
            options={
                'verbose_name': 'Item Beck',
                'verbose_name_plural': 'Items Beck',
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='PhraseBeck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_valeur', models.IntegerField(help_text='Valeur du score (0, 1, 2 ou 3)', verbose_name='Score')),
                ('texte', models.TextField(verbose_name='Texte de la phrase')),
                ('ordre', models.IntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phrases', to='tests_psy.itembeck', verbose_name='Item')),
            ],
            options={
                'verbose_name': 'Phrase Beck',
                'verbose_name_plural': 'Phrases Beck',
                'ordering': ['item__numero', 'ordre'],
                'unique_together': {('item', 'ordre')},
            },
        ),
        migrations.CreateModel(
            name='TestBeck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_passation', models.DateTimeField(auto_now_add=True, verbose_name='Date de passation')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('score_total', models.IntegerField(default=0, help_text='Score total sur 63 points', verbose_name='Score total')),
                ('niveau_depression', models.CharField(blank=True, max_length=20, verbose_name='Niveau de dépression')),
                ('alerte_suicide', models.BooleanField(default=False, help_text="True si l'item 9 a un score >= 2", verbose_name='Alerte idées suicidaires')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.organization', verbose_name='Organisation')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests_%(class)s', to='cabinet.patient', verbose_name='Patient')),
                ('psychologue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Psychologue')),
            ],
            options={
                'verbose_name': 'Test Beck',
                'verbose_name_plural': 'Tests Beck',
                'ordering': ['-date_passation'],
            },
        ),
        migrations.CreateModel(
            name='ReponseItemBeck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_item', models.IntegerField(default=0, help_text='Score maximum des phrases cochées', verbose_name="Score de l'item")),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests_psy.itembeck', verbose_name='Item')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.organization', verbose_name='Organisation')),
                ('phrases_cochees', models.ManyToManyField(help_text='Le patient peut cocher plusieurs phrases', to='tests_psy.phrasebeck', verbose_name='Phrases cochées')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reponses', to='tests_psy.testbeck', verbose_name='Test')),
            ],
            options={
                'verbose_name': 'Réponse Item Beck',
                'verbose_name_plural': 'Réponses Items Beck',
                'ordering': ['item__numero'],
                'unique_together': {('test', 'item')},
            },
        ),
    ]
