# Generated by Django 5.2.7 on 2025-12-01 18:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('cabinet', '0001_initial'),
        ('tests_psy', '0004_itembeck_phrasebeck_testbeck_reponseitembeck'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemSTAI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(unique=True, verbose_name="Numéro de l'item")),
                ('texte', models.TextField(verbose_name="Texte de l'item")),
                ('section', models.CharField(
                    choices=[('ETAT', 'État (Y1)'), ('TRAIT', 'Trait (Y2)')],
                    max_length=10,
                    verbose_name='Section',
                    help_text='ÉTAT (situationnel) ou TRAIT (habituel)'
                )),
                ('est_inverse', models.BooleanField(
                    default=False,
                    verbose_name='Item inversé',
                    help_text='Si True, le score est inversé (1→4, 2→3, 3→2, 4→1)'
                )),
            ],
            options={
                'verbose_name': 'Item STAI',
                'verbose_name_plural': 'Items STAI',
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='TestSTAI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date_passation', models.DateTimeField(auto_now_add=True, verbose_name='Date de passation')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('score_etat', models.IntegerField(default=0, verbose_name='Score ÉTAT (Y1)', help_text='Score anxiété situationnelle (20-80)')),
                ('score_trait', models.IntegerField(default=0, verbose_name='Score TRAIT (Y2)', help_text='Score anxiété générale (20-80)')),
                ('niveau_anxiete_etat', models.CharField(blank=True, max_length=20, verbose_name='Niveau anxiété ÉTAT')),
                ('niveau_anxiete_trait', models.CharField(blank=True, max_length=20, verbose_name='Niveau anxiété TRAIT')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests_teststai', to='core.organization')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests_teststai', to='cabinet.patient', verbose_name='Patient')),
                ('psychologue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Psychologue')),
            ],
            options={
                'verbose_name': 'Test STAI',
                'verbose_name_plural': 'Tests STAI',
                'ordering': ['-date_passation'],
            },
        ),
        migrations.CreateModel(
            name='ReponseItemSTAI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('valeur_choisie', models.IntegerField(verbose_name='Valeur choisie', help_text='Valeur brute choisie par le patient (1, 2, 3 ou 4)')),
                ('score_calcule', models.IntegerField(default=0, verbose_name='Score calculé', help_text='Score après inversion si nécessaire')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reponseitems tais', to='core.organization')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests_psy.itemstai', verbose_name='Item')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reponses', to='tests_psy.teststai', verbose_name='Test')),
            ],
            options={
                'verbose_name': 'Réponse Item STAI',
                'verbose_name_plural': 'Réponses Items STAI',
                'ordering': ['item__numero'],
            },
        ),
        migrations.AddConstraint(
            model_name='reponseitems tai',
            constraint=models.UniqueConstraint(fields=['test', 'item'], name='unique_test_item_stai'),
        ),
    ]
