# Generated by Django 5.2.7 on 2025-12-01 19:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_license_has_beck_license_max_tests_beck'),
        ('cabinet', '0001_initial'),
        ('tests_psy', '0004_itembeck_phrasebeck_testbeck_reponseitembeck'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemSTAI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(unique=True, verbose_name="Numéro de l'item")),
                ('texte', models.TextField(verbose_name="Texte de l'item")),
                ('section', models.CharField(choices=[('ETAT', 'État (Y1)'), ('TRAIT', 'Trait (Y2)')], help_text='ÉTAT (situationnel) ou TRAIT (habituel)', max_length=10, verbose_name='Section')),
                ('est_inverse', models.BooleanField(default=False, help_text='Si True, le score est inversé (1→4, 2→3, 3→2, 4→1)', verbose_name='Item inversé')),
            ],
            options={
                'verbose_name': 'Item STAI',
                'verbose_name_plural': 'Items STAI',
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='TestSTAI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_passation', models.DateTimeField(auto_now_add=True, verbose_name='Date de passation')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('score_etat', models.IntegerField(default=0, help_text='Score anxiété situationnelle (20-80)', verbose_name='Score ÉTAT (Y1)')),
                ('score_trait', models.IntegerField(default=0, help_text='Score anxiété générale (20-80)', verbose_name='Score TRAIT (Y2)')),
                ('niveau_anxiete_etat', models.CharField(blank=True, max_length=20, verbose_name='Niveau anxiété ÉTAT')),
                ('niveau_anxiete_trait', models.CharField(blank=True, max_length=20, verbose_name='Niveau anxiété TRAIT')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.organization', verbose_name='Organisation')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests_%(class)s', to='cabinet.patient', verbose_name='Patient')),
                ('psychologue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Psychologue')),
            ],
            options={
                'verbose_name': 'Test STAI',
                'verbose_name_plural': 'Tests STAI',
                'ordering': ['-date_passation'],
            },
        ),
        migrations.CreateModel(
            name='ReponseItemSTAI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valeur_choisie', models.IntegerField(help_text='Valeur brute choisie par le patient (1, 2, 3 ou 4)', verbose_name='Valeur choisie')),
                ('score_calcule', models.IntegerField(default=0, help_text='Score après inversion si nécessaire', verbose_name='Score calculé')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests_psy.itemstai', verbose_name='Item')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.organization', verbose_name='Organisation')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reponses', to='tests_psy.teststai', verbose_name='Test')),
            ],
            options={
                'verbose_name': 'Réponse Item STAI',
                'verbose_name_plural': 'Réponses Items STAI',
                'ordering': ['item__numero'],
                'unique_together': {('test', 'item')},
            },
        ),
    ]
