# Generated by Django 5.2.7 on 2026-09-15 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_user_can_access_agenda_user_can_access_beck_and_more'),
        ('tests_psy', '0005_itemstai_teststai_reponseitemstai'),
    ]

    operations = [
        migrations.AddField(
            model_name='testvineland',
            name='lien_duree_jours',
            field=models.PositiveIntegerField(blank=True, help_text='Réutilisée si le psychologue réouvre le lien plus tard.', null=True, verbose_name='Durée choisie du lien (jours)'),
        ),
        migrations.AddField(
            model_name='testvineland',
            name='lien_expire_le',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Expiration du lien'),
        ),
        migrations.AddField(
            model_name='testvineland',
            name='lien_soumis_le',
            field=models.DateTimeField(blank=True, help_text='Non vide = lien verrouillé (le parent ne peut plus modifier).', null=True, verbose_name='Soumis par le parent le'),
        ),
        migrations.AddField(
            model_name='testvineland',
            name='lien_token',
            field=models.CharField(blank=True, max_length=43, null=True, unique=True, verbose_name='Jeton du lien public'),
        ),
        migrations.AddField(
            model_name='testvineland',
            name='mode',
            field=models.CharField(choices=[('cabinet', 'Passation en cabinet'), ('importe', 'Notes importées'), ('lien_public', 'Lien envoyé aux parents')], default='cabinet', max_length=15, verbose_name='Mode de passation'),
        ),
        migrations.CreateModel(
            name='NoteBruteImporteeVineland',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_brute', models.PositiveIntegerField(verbose_name='Note brute')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.organization', verbose_name='Organisation')),
                ('sous_domaine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes_brutes_importees', to='tests_psy.sousdomain')),
                ('test_vineland', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes_brutes_importees', to='tests_psy.testvineland', verbose_name='Test Vineland')),
            ],
            options={
                'verbose_name': 'Note brute importée (Vineland)',
                'verbose_name_plural': 'Notes brutes importées (Vineland)',
                'unique_together': {('test_vineland', 'sous_domaine')},
            },
        ),
    ]
