# Generated by Django 5.2.7 on 2026-09-19 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests_psy', '0006_testvineland_lien_duree_jours_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testd2r',
            name='code',
            field=models.CharField(blank=True, max_length=50, verbose_name='Code du test'),
        ),
    ]
