# Generated by Django 5.2.7 on 2025-10-14 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='license',
            name='max_tests_per_month',
        ),
        migrations.AlterField(
            model_name='license',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de fin (null = illimité)'),
        ),
        migrations.AlterField(
            model_name='license',
            name='max_patients',
            field=models.IntegerField(default=10, verbose_name='Nombre max de patients (trial uniquement)'),
        ),
        migrations.AlterField(
            model_name='license',
            name='plan',
            field=models.CharField(choices=[('trial', 'Essai gratuit (30 jours)'), ('lifetime', 'Licence complète (achat unique)')], default='trial', max_length=20),
        ),
    ]
