# Generated by Django 5.2.7 on 2025-10-14 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_license_max_tests_per_month_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='max_patients',
            field=models.IntegerField(default=10, verbose_name='Nombre max de patients'),
        ),
    ]
