# Generated by Django 5.2.7 on 2025-10-17 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_license_max_patients'),
    ]

    operations = [
        migrations.AddField(
            model_name='license',
            name='has_d2r',
            field=models.BooleanField(default=False, verbose_name='Accès Test D2R'),
        ),
        migrations.AddField(
            model_name='license',
            name='has_pep3',
            field=models.BooleanField(default=False, verbose_name='Accès Test PEP3'),
        ),
        migrations.AddField(
            model_name='license',
            name='has_vineland',
            field=models.BooleanField(default=False, verbose_name='Accès Test Vineland'),
        ),
    ]
