# Generated by Django 5.2.7 on 2025-10-17 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_license_has_d2r_license_has_pep3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='license',
            name='max_tests_d2r',
            field=models.IntegerField(default=0, verbose_name='Nombre max de tests D2R (0 = illimité)'),
        ),
        migrations.AddField(
            model_name='license',
            name='max_tests_pep3',
            field=models.IntegerField(default=0, verbose_name='Nombre max de tests PEP3 (0 = illimité)'),
        ),
        migrations.AddField(
            model_name='license',
            name='max_tests_vineland',
            field=models.IntegerField(default=0, verbose_name='Nombre max de tests Vineland (0 = illimité)'),
        ),
    ]
