# Generated by Django 5.2.7 on 2025-11-30 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_license_max_tests_d2r_license_max_tests_pep3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='license',
            name='has_beck',
            field=models.BooleanField(default=False, verbose_name='Accès Test Beck'),
        ),
        migrations.AddField(
            model_name='license',
            name='max_tests_beck',
            field=models.IntegerField(default=0, verbose_name='Nombre max de tests Beck (0 = illimité)'),
        ),
    ]
