# Generated by Django 5.2.7 on 2025-12-01 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_license_has_beck_license_max_tests_beck'),
    ]

    operations = [
        migrations.AddField(
            model_name='license',
            name='has_stai',
            field=models.BooleanField(default=False, verbose_name='Accès Test STAI'),
        ),
        migrations.AddField(
            model_name='license',
            name='max_tests_stai',
            field=models.IntegerField(default=0, verbose_name='Nombre max de tests STAI (0 = illimité)'),
        ),
    ]
