# Generated by Django 5.2.7 on 2026-09-12 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_license_has_stai_license_max_tests_stai'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_export_backup',
            field=models.BooleanField(default=False, help_text='À cocher uniquement pour les personnes de confiance : exporte toutes les données patients.', verbose_name='Autorisé à exporter les sauvegardes'),
        ),
    ]
