# Generated by Django 5.2.7 on 2026-09-12 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_can_export_backup'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='ics_token',
            field=models.CharField(blank=True, help_text="Utilisé dans le lien secret d'abonnement à l'agenda (.ics). Régénérable en cas de fuite.", max_length=43, null=True, unique=True, verbose_name='Jeton de synchronisation calendrier'),
        ),
    ]
