# Generated by Django 5.2.7 on 2026-09-14 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_organization_ics_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_access_agenda',
            field=models.BooleanField(default=True, verbose_name="Accès à l'onglet Agenda"),
        ),
        migrations.AddField(
            model_name='user',
            name='can_access_beck',
            field=models.BooleanField(default=True, verbose_name='Accès au test Beck'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_access_comptabilite',
            field=models.BooleanField(default=True, verbose_name="Accès à l'onglet Comptabilité"),
        ),
        migrations.AddField(
            model_name='user',
            name='can_access_consultations',
            field=models.BooleanField(default=True, verbose_name="Accès à l'onglet Consultations"),
        ),
        migrations.AddField(
            model_name='user',
            name='can_access_d2r',
            field=models.BooleanField(default=True, verbose_name='Accès au test D2R'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_access_patients',
            field=models.BooleanField(default=True, verbose_name="Accès à l'onglet Patients"),
        ),
        migrations.AddField(
            model_name='user',
            name='can_access_stai',
            field=models.BooleanField(default=True, verbose_name='Accès au test STAI'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_access_tags',
            field=models.BooleanField(default=True, verbose_name="Accès à l'onglet Tags"),
        ),
        migrations.AddField(
            model_name='user',
            name='can_access_vineland',
            field=models.BooleanField(default=True, verbose_name='Accès au test Vineland'),
        ),
    ]
