# Generated by Django 5.2.7 on 2026-09-17 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_user_can_access_agenda_user_can_access_beck_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='license',
            name='dernier_paiement_le',
            field=models.DateField(blank=True, null=True, verbose_name='Dernier paiement le'),
        ),
        migrations.AddField(
            model_name='license',
            name='prix_dhs',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Montant du cycle de facturation (mensuel ou annuel), pour ton suivi.', max_digits=8, null=True, verbose_name='Prix (DHS)'),
        ),
        migrations.AlterField(
            model_name='license',
            name='plan',
            field=models.CharField(choices=[('trial', 'Essai gratuit (30 jours)'), ('lifetime', 'Licence complète (achat unique)'), ('abonnement_mensuel', 'Abonnement mensuel'), ('abonnement_annuel', 'Abonnement annuel')], default='trial', max_length=20),
        ),
    ]
