# Generated by Django 5.2.7 on 2026-09-17 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_license_dernier_paiement_le_license_prix_dhs_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaiementLicence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_paiement', models.DateField()),
                ('montant', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('plan', models.CharField(choices=[('trial', 'Essai gratuit (30 jours)'), ('lifetime', 'Licence complète (achat unique)'), ('abonnement_mensuel', 'Abonnement mensuel'), ('abonnement_annuel', 'Abonnement annuel')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('license', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='accounts.license')),
            ],
            options={
                'verbose_name': 'Paiement de licence',
                'verbose_name_plural': 'Paiements de licence',
                'ordering': ['-date_paiement', '-created_at'],
            },
        ),
    ]
