# Generated by Django 5.2.7 on 2026-09-09 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultation',
            name='pack_mind_office_utilise',
        ),
        migrations.DeleteModel(
            name='PackMindOffice',
        ),
    ]
