# Generated by Django 5.2.7 on 2026-09-09 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0002_remove_consultation_pack_mind_office_utilise_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='lieu_consultation',
            field=models.CharField(choices=[('visio', 'Visioconférence'), ('bouskoura', 'Cabinet Bouskoura'), ('mind_office', 'Cabinet')], default='visio', max_length=20, verbose_name='Lieu de consultation'),
        ),
    ]
