# Generated by Django 5.2.7 on 2026-09-12 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_license_has_stai_license_max_tests_stai'),
        ('cabinet', '0003_alter_consultation_lieu_consultation'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom du modèle')),
                ('type_rappel', models.CharField(choices=[('j-1', 'Rappel J-1 (veille)'), ('h-1', 'Rappel H-1 (1h avant)'), ('autre', 'Autre')], default='j-1', max_length=10)),
                ('contenu', models.TextField(help_text='Variables disponibles : {patient}, {date}, {heure}, {psychologue}, {lieu}', verbose_name='Contenu du message')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.organization', verbose_name='Organisation')),
            ],
            options={
                'verbose_name': 'Modèle de message',
                'verbose_name_plural': 'Modèles de messages',
                'ordering': ['type_rappel', 'nom'],
            },
        ),
    ]
