# Generated by Django 5.2.7 on 2026-09-12 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0005_consultation_note_evaluation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='visio_room',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Salle de visioconférence'),
        ),
    ]
