# Generated by Django 5.2.7 on 2026-09-12 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0006_consultation_visio_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagetemplate',
            name='contenu',
            field=models.TextField(help_text='Variables disponibles : {patient}, {date}, {heure}, {psychologue}, {lieu}, {lien_visio}', verbose_name='Contenu du message'),
        ),
        migrations.AlterField(
            model_name='messagetemplate',
            name='type_rappel',
            field=models.CharField(choices=[('j-1', 'Rappel J-1 (veille)'), ('h-1', 'Rappel H-1 (1h avant)'), ('visio', 'Rappel visio (avec lien)'), ('autre', 'Autre')], default='j-1', max_length=10),
        ),
    ]
