# Generated by Django 5.2.7 on 2026-09-12 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_license_has_stai_license_max_tests_stai'),
        ('cabinet', '0007_alter_messagetemplate_contenu_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Depense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorie', models.CharField(choices=[('loyer', 'Loyer'), ('materiel', 'Matériel'), ('logiciel', 'Logiciels / Abonnements'), ('deplacement', 'Déplacement'), ('formation', 'Formation'), ('autre', 'Autre')], default='autre', max_length=20)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant (DHS)')),
                ('date_depense', models.DateField(verbose_name='Date de la dépense')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.organization', verbose_name='Organisation')),
            ],
            options={
                'verbose_name': 'Dépense',
                'verbose_name_plural': 'Dépenses',
                'ordering': ['-date_depense'],
                'indexes': [models.Index(fields=['organization', '-date_depense'], name='cabinet_dep_organiz_04663e_idx')],
            },
        ),
    ]
