# Generated by Django 5.2.7 on 2026-09-12 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_can_export_backup'),
        ('cabinet', '0008_depense'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('couleur', models.CharField(default='#e879f9', max_length=7, verbose_name='Couleur (hex)')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.organization', verbose_name='Organisation')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'ordering': ['nom'],
            },
        ),
        migrations.AddField(
            model_name='patient',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='patients', to='cabinet.tag'),
        ),
        migrations.CreateModel(
            name='Indisponibilite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=150)),
                ('type_absence', models.CharField(choices=[('formation', 'Formation'), ('deplacement', 'Déplacement'), ('conge', 'Congé'), ('autre', 'Autre')], default='autre', max_length=20)),
                ('date_debut', models.DateTimeField()),
                ('date_fin', models.DateTimeField()),
                ('note', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.organization', verbose_name='Organisation')),
            ],
            options={
                'verbose_name': 'Indisponibilité',
                'verbose_name_plural': 'Indisponibilités',
                'ordering': ['date_debut'],
                'indexes': [models.Index(fields=['organization', 'date_debut'], name='cabinet_ind_organiz_a67d4e_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='tag',
            constraint=models.UniqueConstraint(fields=('organization', 'nom'), name='unique_tag_par_organisation'),
        ),
    ]
