# Generated by Django 5.2.7 on 2026-09-12 23:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0009_tag_patient_tags_indisponibilite_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PushSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.URLField(max_length=500, unique=True)),
                ('p256dh', models.CharField(max_length=255)),
                ('auth', models.CharField(max_length=255)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Abonnement notification push',
                'verbose_name_plural': 'Abonnements notifications push',
            },
        ),
        migrations.CreateModel(
            name='RappelEnvoye',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_rappel', models.CharField(default='1h_avant', max_length=20)),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rappels_envoyes', to='cabinet.consultation')),
            ],
            options={
                'verbose_name': 'Rappel push envoyé',
                'verbose_name_plural': 'Rappels push envoyés',
                'constraints': [models.UniqueConstraint(fields=('consultation', 'type_rappel'), name='unique_rappel_par_consultation')],
            },
        ),
    ]
